package com.dub.digital;

import java.util.Scanner;
import java.util.Random;

public class Game {

    public int startGame(){
        Scanner scanner = new Scanner(System.in);

        //start game

        //create a variable to hold the user reponse using the Scanner object.
        // The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        int userChoice = scanner.nextInt();
        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuChoice = getCPUResponse();
        int showDown = 0;
        //compare user and cpu response with each other to decide the winner.

        switch (userChoice){
            case 1: Rock r = new Rock(cpuChoice);
                result = r.checkOutcome();
                break;
            case 2: Paper p = new Paper(cpuChoice);
                result = p.checkOutcome();
                break;
            case 3: Scissors s = new Scissors(cpuChoice);
                result = s.checkOutcome();
                break;
            default:
                System.out.println("Please choose a different response");

        }

/* I made the wrong comparison at first. But I didn't want to delete this code. I want to
refactor this and try writing this program another way.
 */
//        if(userChoice > cpuChoice){
//            System.out.println("User Wins, You're Awesome");
//        } else if(userChoice < cpuChoice){
//            System.out.println("CPU Wins, You're Awesome");
//        } else (userChoice == cpuChoice){
//            System.out.println("We Have A Draw!!!");
//        }

        //TODO: collect points for score
        if (showDown > 0){
            System.out.println("User Wins, You're Awesome");
        } else {
            System.out.println("CPU Wins, You're Awesome");
        }
        return showDown;
    }

    public int getCPUResponse() {
        // Generate random integers in range 1 to 3
        Random random = new Random();
        int first = 1;
        int second = 3;

        int result = random.nextInt(second-first) + first;

        return result;
    }
}
