package com.dub.digital;

import java.util.Scanner;
import java.util.Random;

public class Game {

    public int startGame(){
        Scanner scanner = new Scanner(System.in);

        //start game

        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        int userChoice = scanner.nextInt();
        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuChoice = getCPUResponse();
        //compare user and cpu response with each other to decide the winner.
        if(userChoice > cpuChoice){
            System.out.println("User Wins, You're Awesome");
            return 1;
        } else if(userChoice < cpuChoice){
            System.out.println("CPU Wins, You're Awesome");
            return 2;
        } else (userChoice == cpuChoice){
            System.out.println("We Have A Draw!!!");
            return 3;
        }
    }

    public int getCPUResponse() {
        // Generate random integers in range 1 to 3
        Random random = new Random();
        int first = 1;
        int second = 3;

        int result = random.nextInt(second-first) + first;

        return result;
    }
}
